// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcPackage.Data;

#nullable disable

namespace MailroomApplication.Migrations
{
    [DbContext(typeof(MvcPackageContext))]
    [Migration("20241206052349_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("MailroomApplication.Models.Package", b =>
                {
                    b.Property<int>("packageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("checkInDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("checkOutDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("postalService")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("residentID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("packageID");

                    b.ToTable("Package");
                });

            modelBuilder.Entity("MailroomApplication.Models.Resident", b =>
                {
                    b.Property<int>("residentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("residentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("unitNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("residentID");

                    b.ToTable("Resident");
                });

            modelBuilder.Entity("MailroomApplication.Models.Staff", b =>
                {
                    b.Property<int>("staffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("staffID");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("MailroomApplication.Models.Unknown", b =>
                {
                    b.Property<int>("unknownID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("packageID")
                        .HasColumnType("INTEGER");

                    b.HasKey("unknownID");

                    b.HasIndex("packageID");

                    b.ToTable("Unknown");
                });

            modelBuilder.Entity("MailroomApplication.Models.Unknown", b =>
                {
                    b.HasOne("MailroomApplication.Models.Package", "Package")
                        .WithMany()
                        .HasForeignKey("packageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });
#pragma warning restore 612, 618
        }
    }
}
